repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: mix-format
        name: Mix Format
        entry: mix format
        language: system
        types: [elixir]
      # - id: mix-compile
      #   name: Mix Compile
      #   entry: mix do deps.clean --all, deps.get, deps.compile --force --warnings-as-errors
      #   language: system
      #   types: [elixir]
      # - id: mix-sobelow
      #   name: Mix Sobelow
      #   entry: mix sobelow --config .sobelow-conf
      #   language: system
      #   types: [elixir]
      - id: credo
        name: Credo Lint
        entry: mix credo
        language: system
        types: [elixir]
      # - id: mix-test
      #   name: Mix Test
      #   entry: mix test
      #   language: system
      #   types: [elixir]
