name: tests

on: [push, pull_request]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - otp: '26.0'
            elixir: '1.15'
          - otp: '27.1'
            elixir: '1.17'
            lint: lint
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
         otp-version: ${{ matrix.otp }}
         elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v3
        with:
         path: deps
         key: ${{ runner.os }}-${{ matrix.elixir }}-otp${{ matrix.otp }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
         restore-keys: |
           ${{ runner.os }}-${{ matrix.elixir }}-otp${{ matrix.otp }}-mix-
      - run: mix deps.get
      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - run: mix credo
        if: ${{ matrix.lint }}

      - run: mix coveralls.github
